# Generated by Django 3.2.12 on 2025-03-02 09:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='graduation_year',
            new_name='enrollment_date',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='cgpa',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='current_level',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='department',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='emergency_contact_name',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='emergency_contact_phone',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='employee_id',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='faculty',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='gender',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='office_location',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='office_phone',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='position',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='profile_picture',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='year_of_entry',
        ),
        migrations.RemoveField(
            model_name='universityprofile',
            name='accreditation_body',
        ),
        migrations.RemoveField(
            model_name='universityprofile',
            name='accreditation_status',
        ),
        migrations.RemoveField(
            model_name='universityprofile',
            name='banner_image',
        ),
        migrations.RemoveField(
            model_name='universityprofile',
            name='city',
        ),
        migrations.RemoveField(
            model_name='universityprofile',
            name='country',
        ),
        migrations.RemoveField(
            model_name='universityprofile',
            name='registration_number',
        ),
        migrations.RemoveField(
            model_name='universityprofile',
            name='social_media_links',
        ),
        migrations.RemoveField(
            model_name='universityprofile',
            name='state',
        ),
        migrations.AddField(
            model_name='profile',
            name='university',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='students', to='accounts.universityprofile'),
        ),
    ]
