# Generated by Django 3.2.12 on 2025-03-04 00:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20250304_0113'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='fullname',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
