# Generated by Django 3.2.12 on 2025-03-04 01:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_student_fullname'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='university',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.universityprofile'),
        ),
        migrations.AddField(
            model_name='user',
            name='is_school_admin',
            field=models.BooleanField(default=True),
        ),
    ]
