# Generated by Django 3.2.12 on 2025-03-04 00:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_student_fullname'),
        ('certificates_database', '0002_alter_certificate_certificate_score'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='certificate',
            name='birth_date',
        ),
        migrations.RemoveField(
            model_name='certificate',
            name='name',
        ),
        migrations.RemoveField(
            model_name='certificate',
            name='subject',
        ),
        migrations.RemoveField(
            model_name='certificate',
            name='surname',
        ),
        migrations.AddField(
            model_name='certificate',
            name='student',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='certificate', to='accounts.student'),
        ),
    ]
