# Generated by Django 3.2.12 on 2025-03-04 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certificates_database', '0003_auto_20250304_0127'),
    ]

    operations = [
        migrations.AddField(
            model_name='certificate',
            name='cert_back',
            field=models.ImageField(blank=True, null=True, upload_to='certificates/'),
        ),
        migrations.AddField(
            model_name='certificate',
            name='cert_front',
            field=models.ImageField(blank=True, null=True, upload_to='certificates/'),
        ),
    ]
