# Generated by Django 3.2.12 on 2025-03-04 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certificates_database', '0005_certificate_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='certificate',
            name='serial_no',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
    ]
